  type User{
        id:ID!
        firstName:String!
        lastName:String!
        email:String!
        password:String!
    }
    input UserInput{
        firstName:String!
        lastName:String!
        email:String!
        password:String!
    }

     input LoginInput{     
        email:String!
        password:String!
    }

    type authUser
    {
        id:ID
        token:String
        firstName:String
        lastName:String
        email:String
    }

    type Query{
        getAllUsers:[User!]!
    }

      type Mutation{   
        registerUser( path : UserInput):User
        loginUser( path :LoginInput):authUser
      }