  type User{
        id:ID!
        firstName:String!
        lastName:String!
        email:String!
        password:String!
    }
    input UserInput{
        firstName:String!
        lastName:String!
        email:String!
        password:String!
    }

     input LoginInput{     
        email:String!
        password:String!
    }

    type authUser
    {
        id:ID
        token:String
        firstName:String
        lastName:String
        email:String
    }

    type Note{
        title:String
        description:String
    }
    input NoteInput{
       title:String!
       description:String!
    }
    input NoteEdit
    {   noteId:String!
        title:String
        description:String
    }
    input DeleteNote 
    {
        noteId:String!
    }

    type Query{
        getAllUsers:[User!]!
        notes:[Note!]!
    }

      type Mutation{   
        registerUser( path : UserInput):User
        loginUser( path :LoginInput):authUser

        createNote(post : NoteInput):Note
        editNote(post : NoteEdit):Note
        deleteNote(post : DeleteNote):Note
    }